version: "3.8"
services:
  frontend:
    container_name: smartbearing-frontend
    command: npm start # 컨테이너가 실행될 때 실행할 명령
    restart: always
    image: chy0503/smartbearing-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    working_dir: /app
  db:
    container_name: smartbearing-database
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=smartbearing
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/config/mysql.cnf:/etc/mysql/my.cnf
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
  redis:
    container_name: smartbearing-redis
    image: redis:alpine
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
  backend:
    container_name: smartbearing-backend
    depends_on:
      - db
      - redis
      - frontend
    image: chy0503/smartbearing-backend
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - "80:8080"
    restart: always
